#!/usr/bin/env python3
"""Validate example documents against the canonical schemas in this package.

Usage: python3 validate.py
Exit 0 if every check passes.

Two schemas live here (added the second):
  ai-usage-event — the collector -> ingest event contract
  security-alert — the cross-pillar unified alert contract (D3.1)

Both use Draft 2020-12 and the same valid-/invalid- example convention, so
adding a schema is a row in SCHEMAS, not a second script.

security-alert ships in TWO forms and picking the wrong one is the
defect (D3.1 §6.1). Cloud Sentry and gatehouse vendor from here — one schema,
one home — but they must vendor the form that matches their role:

  security-alert.schema.json           PUBLISHERS validate against this.
  security-alert.consumer.schema.json  CONSUMERS validate against this. It is
                                       generated by consumer_profile() below
                                       (--write-consumer-profile); CI fails if
                                       the committed file drifts from it.

A consumer that vendors the strict schema drops every alert from the first
additive minor bump — silently, since a dropped alert looks like no alert.

security-alert carries two checks the event schema does not need: the derived
consumer profile (see consumer_profile) and a replay of the adversarial
conformance corpus every bus consumer must pass (D3.1 §12 item 9).
"""
import copy
import json
import pathlib
import re
import sys

from jsonschema import Draft202012Validator
from jsonschema.exceptions import SchemaError

HERE = pathlib.Path(__file__).resolve().parent
CONFORMANCE = HERE / "conformance"

# The derivation's output, committed so a non-Python consumer can validate
# against the profile without reimplementing consumer_profile() — a
# reimplementation is the fork §6.1 forbids, just written in another language.
# Regenerate with `validate.py --write-consumer-profile`; CI fails if the
# committed file and the derivation disagree, so the artifact cannot drift.
CONSUMER_PROFILE = HERE / "schema" / "v1" / "security-alert.consumer.schema.json"

# (name, schema path, examples directory). Examples are matched non-recursively
# so each schema owns exactly one directory.
SCHEMAS = [
    ("ai-usage-event", HERE / "schema" / "v1" / "ai-usage-event.schema.json", HERE / "examples"),
    ("security-alert", HERE / "schema" / "v1" / "security-alert.schema.json",
     HERE / "examples" / "security-alert"),
]


def check_one(name: str, schema_path: pathlib.Path, examples: pathlib.Path) -> int:
    """Validate one schema's example set. Returns the failure count."""
    schema = json.loads(schema_path.read_text())
    try:
        Draft202012Validator.check_schema(schema)
    except SchemaError as e:
        print(f"SCHEMA INVALID ({name}): {e.message}")
        return 1
    validator = Draft202012Validator(schema)

    print(f"\n== {name} ({schema_path.relative_to(HERE)})")
    failures = 0
    paths = sorted(examples.glob("*.json"))
    if not paths:
        print(f"FAIL {name}: no examples found in {examples.relative_to(HERE)}")
        return 1
    for path in paths:
        document = json.loads(path.read_text())
        errors = sorted(validator.iter_errors(document), key=lambda e: list(e.path))
        expect_valid = path.name.startswith("valid-")
        if expect_valid and errors:
            failures += 1
            print(f"FAIL {path.name}: expected valid, got {len(errors)} error(s)")
            for e in errors:
                print(f"  - {list(e.path)}: {e.message}")
        elif not expect_valid and not errors:
            failures += 1
            print(f"FAIL {path.name}: expected REJECTION but it validated")
        else:
            verdict = "valid" if expect_valid else "rejected"
            print(f"ok   {path.name}: {verdict} as expected"
                  + ("" if expect_valid else f" ({errors[0].message[:80]})"))
    return failures


# --------------------------------------------------------------------------
# security.alert/v1 only: consumer profile, cross-field invariants, corpus.
# --------------------------------------------------------------------------

# Open-vocabulary fields: a closed enum for a publisher, a free string for a
# consumer. See consumer_profile(). Paths are keys under "properties".
OPEN_VOCABULARY = [
    ("pillar",),
    ("severity",),
    ("status",),
    ("resource", "kind"),
    ("resource", "provider"),
]

SEVERITY_ID = {"critical": 5, "high": 4, "medium": 3, "low": 2, "informational": 1}


def consumer_profile(schema: dict) -> dict:
    """Derive the consumer-side profile of the strict publisher schema.

    D3.1 §6 makes minor versions additive-only, and §7.4 tells consumers to
    ignore unknown fields and degrade unknown enum values — but §7.10 tells
    them to validate every entry against the schema and drop what fails.
    Against a *single* strict schema those rules contradict each other: a v1.2
    alert carrying one new optional field, or one new severity value, is
    schema-invalid to a v1.1 consumer, so §7.10 makes it drop exactly the alert
    §7.4 says to keep — and minor bumps stop being additive in practice, which
    is the whole property §6 exists to provide. Corpus lines 6-8 demonstrate it.

    The resolution is Postel's law with the security constraints kept on both
    sides:

      * publishers validate strictly — a typo'd field name is a publisher bug
        and must fail loudly at publish time, nearest the code that caused it;
      * consumers validate leniently in exactly two respects — unknown fields
        are ignored, and open-vocabulary enums accept unknown members.

    Everything that is a *security* constraint stays strict for both: the
    source_uri pattern (traversal / open redirect), the pseudonym pattern
    (plaintext identity), required fields, types, and the length caps. A
    consumer that relaxed those would be validating nothing that matters.

    Derived, never forked, so §6's "one schema, one home" still holds.
    """
    profile = copy.deepcopy(schema)
    profile["$id"] = profile["$id"].replace(
        "security-alert.schema.json", "security-alert.consumer.schema.json")
    profile["title"] += " (consumer profile)"

    def open_up(node):
        if isinstance(node, dict):
            if node.get("additionalProperties") is False:
                node["additionalProperties"] = True
            for value in node.values():
                open_up(value)
        elif isinstance(node, list):
            for item in node:
                open_up(item)

    open_up(profile)
    for path in OPEN_VOCABULARY:
        node = profile
        for key in path:
            node = node["properties"][key]
        node.pop("enum", None)
    return profile


def profile_bytes(profile: dict) -> str:
    """The committed artifact's canonical serialization. One writer, one reader."""
    return json.dumps(profile, indent=2, sort_keys=False) + "\n"


_MISSING = object()


def where(path: tuple) -> str:
    """The one spelling of a schema location used by every check below.

    Not two. The first version of the closed-object check compared paths spelled
    "" against paths spelled "(root)" and reported the root object as never
    opened when it always was -- a set comparison between two vocabularies that
    only overlap by accident is the same defect these checks exist to catch,
    committed in the checker itself.
    """
    return "/".join(path) or "(root)"


def profile_path(path: tuple) -> str:
    """OPEN_VOCABULARY tuple -> the path form the checks report."""
    return where(tuple(part for key in path for part in ("properties", key)))


def closed_paths(schema: dict, keyword: str) -> set:
    """Every path in `schema` that closes something, in profile_path form.

    `keyword` is "enum" (a closed vocabulary — presence closes it) or
    "additionalProperties" (a closed object — only `false` closes it; the
    schema-valued form on `labels` constrains values, not which keys may
    appear, so it is not a closure and the derivation leaves it alone).

    Walked over the *strict* schema rather than diffed against the profile: a
    closure the derivation never touches leaves no trace in the diff, so
    diffing the two schemas cannot see it. That is the failure this exists to
    catch — a closure added to the strict schema and not opened for consumers
    means the first additive member or field under it is dropped by every
    consumer that shipped before it, silently.
    """
    found = set()
    closes = (lambda node: keyword in node) if keyword == "enum" else (
        lambda node: node.get(keyword) is False)

    def walk(node, path):
        if isinstance(node, dict):
            if closes(node):
                found.add(where(path))
            for key, value in node.items():
                walk(value, path + (key,))
        elif isinstance(node, list):
            for i, item in enumerate(node):
                walk(item, path + (str(i),))

    walk(schema, ())
    return found


def derivation_diff(strict: dict, profile: dict) -> tuple:
    """Every way the profile differs from the strict schema, as three sets.

    Returns (opened, enums_dropped, unsanctioned) of JSON-pointer-ish paths.
    D3.1 §6 amendment 2 bounds the split to exactly two relaxations — closed
    objects opened, enum vocabularies dropped — and freezes everything else for
    the major. `unsanctioned` is any other difference, and it must be empty:

      * a relaxation that leaks into the profile only (a widened source_uri
        pattern, a raised label cap, a dropped `required` entry) is a fork
        wearing a derivation's clothes. It would pass every corpus line while
        quietly making consumers validate less than the contract says they do;
      * a *strict* enum with no profile counterpart in OPEN_VOCABULARY is the
        same bug from the other end: the field stays closed for consumers, so
        the first minor version that adds a member to it gets dropped by every
        consumer built before it — the defect, one field at a time.

    Cheap to check, and it is the only check here that fails on code a reviewer
    would otherwise have to catch by eye.
    """
    opened, enums_dropped, unsanctioned = [], [], []

    def walk(a, b, path):
        loc = where(path)
        if isinstance(a, dict) and isinstance(b, dict):
            for key in sorted(set(a) | set(b)):
                at, bt = a.get(key, _MISSING), b.get(key, _MISSING)
                if at == bt:
                    continue
                if key == "additionalProperties" and at is False and bt is True:
                    opened.append(loc)
                elif key == "enum" and bt is _MISSING:
                    enums_dropped.append(loc)
                elif key in ("$id", "title") and not path:
                    continue  # renamed on purpose, so the two cannot be confused
                elif _MISSING in (at, bt):
                    unsanctioned.append(f"{loc}: {key} added/removed")
                else:
                    walk(at, bt, path + (key,))
        elif isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
            for i, (x, y) in enumerate(zip(a, b)):
                walk(x, y, path + (str(i),))
        else:
            unsanctioned.append(f"{loc}: {a!r} -> {b!r}")

    walk(strict, profile, ())
    return opened, enums_dropped, unsanctioned


def cross_field_invariants(alert: dict) -> list:
    """D3.1 §3 rules JSON Schema cannot express. Returns the violations."""
    problems = []
    if SEVERITY_ID.get(alert.get("severity")) != alert.get("severity_id"):
        problems.append("severity/severity_id disagree (§3.2)")
    if str(alert.get("finding_type", "")).split(".")[0] != alert.get("pillar"):
        problems.append("finding_type namespace != pillar (§3.1)")
    if alert.get("first_seen_at", "") > alert.get("last_seen_at", ""):
        problems.append("first_seen_at after last_seen_at (§3.1)")
    evidence = alert.get("evidence") or {}
    if evidence.get("detail_count", 1) > 1 and "?" not in str(evidence.get("source_uri", "")):
        problems.append("detail_count > 1 needs the query form of source_uri (§3.4)")
    # §3.1.1(e): observed_count is the count you maintain, or omitted — never a
    # literal 1 standing in for "I did not count". The placeholder is invisible
    # in general (a real 1 and a fake 1 are the same byte), but it contradicts
    # itself the moment the alert also claims a span: something was seen at
    # last_seen_at and something else at first_seen_at, so the honest count is
    # >= 2. Omitting the field is always available and always passes.
    if (alert.get("observed_count") == 1
            and alert.get("first_seen_at", "") < alert.get("last_seen_at", "")):
        problems.append("observed_count 1 over a first_seen..last_seen span (§3.1.1(e))")
    return problems


def check_alert_contract(schema_path: pathlib.Path, examples: pathlib.Path) -> int:
    """Consumer profile + §10 invariants + corpus replay. Returns failures."""
    failures = 0

    def report(ok: bool, message: str) -> None:
        nonlocal failures
        print(f"{'ok   ' if ok else 'FAIL '}{message}")
        if not ok:
            failures += 1

    print("\n== security-alert: consumer profile, invariants, conformance corpus")
    strict_schema = json.loads(schema_path.read_text())
    profile = consumer_profile(strict_schema)
    try:
        Draft202012Validator.check_schema(profile)
        report(True, "consumer profile is a valid JSON Schema")
    except SchemaError as e:
        report(False, f"consumer profile INVALID: {e.message}")
        return failures
    strict = Draft202012Validator(strict_schema)
    lenient = Draft202012Validator(profile)

    # §6 amendment 2 — the profile is derived, and only in the two sanctioned
    # ways. Without this the corpus still passes while the profile drifts into a
    # fork: relaxing a security constraint for consumers, or leaving a new enum
    # closed so its first additive member is dropped by every older consumer.
    opened, enums_dropped, unsanctioned = derivation_diff(strict_schema, profile)
    report(not unsanctioned,
           "derivation: no relaxation outside enum + additionalProperties"
           + (f" — {unsanctioned}" if unsanctioned else ""))
    declared = {profile_path(p) for p in OPEN_VOCABULARY}
    closed = closed_paths(strict_schema, "enum")
    report(closed == declared,
           f"derivation: every strict enum is declared open-vocabulary ({len(closed)})"
           + (f" — undeclared: {sorted(closed - declared)}, stale: {sorted(declared - closed)}"
              if closed != declared else ""))
    report(set(enums_dropped) == declared,
           f"derivation: all {len(declared)} declared enums opened in the profile"
           + (f" — not opened: {sorted(declared - set(enums_dropped))}"
              if set(enums_dropped) != declared else ""))
    # EVERY closed object, not merely one. `if opened:` passes on a derivation
    # that opens the root and leaves `resource`, `evidence`, `producer` and
    # `subject_ref` closed -- and the whole corpus passes with it, because no
    # corpus line carries its unknown field inside a nested object. That is
    # scoped to a subobject: a v1.2 alert adding one optional field
    # under `resource` is rejected by the profile and dropped in silence.
    # Corpus line 23 is the missing line; this is the assertion that does not
    # depend on someone having written it.
    closed_objects = closed_paths(strict_schema, "additionalProperties")
    report(set(opened) == closed_objects,
           f"derivation: all {len(closed_objects)} closed object(s) opened for consumers"
           + (f" — still closed: {sorted(closed_objects - set(opened))}"
              if set(opened) != closed_objects else ""))

    # The committed artifact must BE the derivation's output. apps/api validates
    # against this file; if it drifts, the JS consumer is silently validating
    # against a stale profile and §6.1's "derived, never forked" is false in the
    # one place it is load-bearing. Byte comparison, so a hand-edit is caught.
    if not CONSUMER_PROFILE.exists():
        report(False, f"consumer profile artifact missing: {CONSUMER_PROFILE.name}"
                      " — run validate.py --write-consumer-profile")
    else:
        report(CONSUMER_PROFILE.read_text() == profile_bytes(profile),
               f"{CONSUMER_PROFILE.name} matches the derivation"
               " (else: --write-consumer-profile)")

    # §10 — the valid fixtures must satisfy the non-schema invariants too.
    for path in sorted(examples.glob("valid-*.json")):
        problems = cross_field_invariants(json.loads(path.read_text()))
        report(not problems,
               f"{path.name}: cross-field invariants" + (f" — {problems}" if problems else ""))

    # §12 item 9 — the corpus every consumer replays. We assert here only the
    # half checkable without a consumer: whether an entry parses, and which
    # profile accepts it. A consumer's own test asserts the manifest's
    # `disposition` — that it deduped, degraded, escaped or counted the entry.
    raw_lines = (CONFORMANCE / "security-alert-v1.ndjson").read_text().splitlines()
    manifest = json.loads(
        (CONFORMANCE / "security-alert-v1.manifest.json").read_text())["entries"]
    report(len(raw_lines) == len(manifest),
           f"corpus: {len(raw_lines)} lines vs {len(manifest)} manifest entries")
    if len(raw_lines) != len(manifest):
        return failures

    # The corpus size is stated in prose in conformance/README.md, and that
    # number has now gone stale twice (21 -> 22 -> 23), each time telling a
    # correct consumer it was broken by exactly one alert. Prose cannot derive
    # it, so CI checks it instead of trusting the next author to remember.
    readme = (CONFORMANCE / "README.md").read_text()
    stated = re.search(r"`security-alert-v1\.ndjson` \| (\d+) entries", readme)
    report(bool(stated) and int(stated.group(1)) == len(raw_lines),
           f"corpus: README states {stated.group(1) if stated else '?'} entries,"
           f" corpus has {len(raw_lines)}")

    # A corpus that drifted back to only happy-path entries would pass vacuously.
    seen = {e["validity"] for e in manifest}
    report(seen == {"publisher-valid", "consumer-only", "invalid", "unparseable"},
           f"corpus: covers all four validity classes ({sorted(seen)})")

    for raw, entry in zip(raw_lines, manifest):
        label = f"corpus {entry['line']:>2} [{entry['rule']}] {entry['case']}"
        validity = entry["validity"]
        try:
            alert = json.loads(raw)
            parsed = isinstance(alert, dict)
        except json.JSONDecodeError:
            parsed = False

        if validity == "unparseable":
            report(not parsed, f"{label}: not a JSON object, as declared")
            continue
        if not parsed:
            report(False, f"{label}: declared {validity} but is not a JSON object")
            continue

        strict_ok = not list(strict.iter_errors(alert))
        lenient_ok = not list(lenient.iter_errors(alert))
        if validity == "publisher-valid":
            report(strict_ok and lenient_ok, f"{label}: accepted by both profiles")
        elif validity == "consumer-only":
            # Load-bearing: forward-compatible entries must be rejected by the
            # strict profile and kept by the consumer one. If strict ever
            # accepts one, the profile split has silently stopped doing work.
            report(not strict_ok and lenient_ok,
                   f"{label}: strict rejects, consumer keeps"
                   + ("" if not strict_ok else " — strict ACCEPTED it, the split is inert"))
        elif validity == "invalid":
            report(not strict_ok and not lenient_ok, f"{label}: rejected by both profiles")
        else:
            report(False, f"{label}: unknown validity {validity!r}")

        # accept-flagged entries exist to prove the invariant checker catches
        # what the schema cannot. If one stops violating an invariant, the
        # checker is being exercised against a clean input and proves nothing.
        if entry["disposition"] == "accept-flagged":
            report(bool(cross_field_invariants(alert)),
                   f"{label}: violates a cross-field invariant, as declared")

    for entry in manifest:
        accepts = entry["disposition"].startswith("accept")
        report(accepts == (entry["validity"] in ("publisher-valid", "consumer-only")),
               f"corpus {entry['line']:>2}: disposition {entry['disposition']}"
               f" agrees with validity {entry['validity']}")
    return failures


def main() -> int:
    _, schema_path, _ = next(r for r in SCHEMAS if r[0] == "security-alert")
    if "--write-consumer-profile" in sys.argv:
        profile = consumer_profile(json.loads(schema_path.read_text()))
        CONSUMER_PROFILE.write_text(profile_bytes(profile))
        print(f"wrote {CONSUMER_PROFILE.relative_to(HERE)}")
        return 0

    failures = sum(check_one(*row) for row in SCHEMAS)
    _, alert_schema, alert_examples = next(r for r in SCHEMAS if r[0] == "security-alert")
    failures += check_alert_contract(alert_schema, alert_examples)
    print(f"\n{failures} failure(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
