#!/usr/bin/env bash
# Build the air-gapped install bundle for the AI Monitoring platform (AIM-98).
#
# Usage: deploy/airgap/build-bundle.sh [version]
#   version defaults to `git describe --tags --always --dirty` (fallback: dev).
#
# Output: deploy/airgap/out/aim-airgap-<version>.tar.gz containing:
#   images.tar            all app + third-party images (docker save)
#   docker-compose.yml    the pinned compose stack, for docker-based targets
#   .env.example          documented env defaults for the compose path
#   chart/aim/            the Helm chart (if deploy/helm/aim exists at build time)
#   install-offline.sh    target-side installer (load images, helm install)
#   README-airgap.md      the operator-facing install doc
#   MANIFEST.txt          image list, sizes, sha256 of every file
#
# Requires: docker (with network access to pull base/third-party images), git.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"
fi

OUT_DIR="deploy/airgap/out"
BUNDLE_NAME="aim-airgap-${VERSION}"
STAGE="$(mktemp -d)/${BUNDLE_NAME}"
mkdir -p "$STAGE" "$OUT_DIR"
trap 'rm -rf "$(dirname "$STAGE")"' EXIT

# Third-party images are extracted from docker-compose.yml (not hardcoded) so
# the bundle can never drift from what `docker compose up` would run. Bundled
# data-plane images: postgres, redis-bus (alert bus), minio, minio/mc.
# Optional SSO proxies stay out of scope (see README-airgap.md).
third_party_images() {
  awk '
    /^  (postgres|redis-bus|minio|minio-init):/ { svc=1; next }
    /^  [a-z][a-z0-9-]*:/ { svc=0 }
    svc && /^    image:/ { sub(/^    image:[[:space:]]*/, ""); print }
  ' docker-compose.yml
}

APP_IMAGES=(
  "aim/ingest:${VERSION}|services/ingest/Dockerfile"
  "aim/api:${VERSION}|apps/api/Dockerfile"
  "aim/guardrail:${VERSION}|services/guardrail/Dockerfile"
)

echo "==> Building app images (version ${VERSION})"
IMAGES=()
for entry in "${APP_IMAGES[@]}"; do
  image="${entry%%|*}"
  dockerfile="${entry##*|}"
  echo "    docker build -t ${image} -f ${dockerfile} ."
  docker build -t "$image" -f "$dockerfile" .
  IMAGES+=("$image")
done

echo "==> Pulling third-party images from docker-compose.yml"
while IFS= read -r image; do
  [[ -z "$image" ]] && continue
  echo "    docker pull ${image}"
  docker pull "$image"
  IMAGES+=("$image")
done < <(third_party_images)

if [[ ${#IMAGES[@]} -eq 0 ]]; then
  echo "error: no images collected; is docker-compose.yml intact?" >&2
  exit 1
fi

echo "==> Saving ${#IMAGES[@]} images to images.tar"
docker save -o "$STAGE/images.tar" "${IMAGES[@]}"

cp deploy/airgap/install-offline.sh "$STAGE/install-offline.sh"
cp docker-compose.yml "$STAGE/docker-compose.yml"
cp .env.example "$STAGE/env.example"
cp docs/deployment/air-gapped-install.md "$STAGE/README-airgap.md"

# Generate a compose override that forces pre-built image tags and clears the
# `build:` keys from docker-compose.yml. Plain `build: null` does NOT work in
# Compose v2+ — the merge keeps the original build context (AIM-599 drill).
# `build: !reset null` is the supported reset. Only the three app services
# shipped in the bundle are overridden; other compose services still require
# source/build and are not part of the offline core path.
echo "==> Writing docker-compose.airgap.yml override for version ${VERSION}"
cat > "$STAGE/docker-compose.airgap.yml" <<EOF
# Generated by deploy/airgap/build-bundle.sh for version ${VERSION}.
# Use with: docker compose -f docker-compose.yml -f docker-compose.airgap.yml up -d
services:
  ingest:
    image: aim/ingest:${VERSION}
    build: !reset null
    pull_policy: never
  api:
    image: aim/api:${VERSION}
    build: !reset null
    pull_policy: never
  guardrail:
    image: aim/guardrail:${VERSION}
    build: !reset null
    pull_policy: never
  postgres:
    pull_policy: never
  redis-bus:
    pull_policy: never
  minio:
    pull_policy: never
  minio-init:
    pull_policy: never
EOF

if [[ -d deploy/helm/aim ]]; then
  echo "==> Including Helm chart deploy/helm/aim"
  mkdir -p "$STAGE/chart"
  cp -r deploy/helm/aim "$STAGE/chart/aim"
  CHART_STATUS="included (deploy/helm/aim)"
else
  echo "warning: deploy/helm/aim not found — bundling WITHOUT the Helm chart." >&2
  echo "         install-offline.sh will skip the helm step on the target." >&2
  CHART_STATUS="NOT included (deploy/helm/aim missing at build time)"
fi

echo "==> Writing MANIFEST.txt"
{
  echo "AIM air-gapped bundle"
  echo "Version: ${VERSION}"
  echo "Built:   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "Helm chart: ${CHART_STATUS}"
  echo
  echo "Images (uncompressed size as reported by docker):"
  for image in "${IMAGES[@]}"; do
    size="$(docker image inspect --format '{{.Size}}' "$image")"
    printf '  %-55s %12s bytes\n' "$image" "$size"
  done
  echo
  echo "Files (sha256):"
  (cd "$STAGE" && find . -type f ! -name MANIFEST.txt -print0 | sort -z | xargs -0 sha256sum | sed 's|  \./|  |')
} > "$STAGE/MANIFEST.txt"

echo "==> Packing ${OUT_DIR}/${BUNDLE_NAME}.tar.gz"
tar -czf "${OUT_DIR}/${BUNDLE_NAME}.tar.gz" -C "$(dirname "$STAGE")" "$BUNDLE_NAME"

BUNDLE_TGZ="${OUT_DIR}/${BUNDLE_NAME}.tar.gz"

# Optional authenticity signature (AIM-747). Private key never enters the stage.
if [[ -n "${AIM_AIRGAP_SIGNING_KEY:-}" ]]; then
  echo "==> Signing bundle with AIM_AIRGAP_SIGNING_KEY (Ed25519)"
  deploy/airgap/sign-bundle.sh "$BUNDLE_TGZ" "$AIM_AIRGAP_SIGNING_KEY"
else
  echo "==> Skipping signature (set AIM_AIRGAP_SIGNING_KEY to auto-sign; AIM-747)"
  echo "    Manual: deploy/airgap/sign-bundle.sh ${BUNDLE_TGZ}"
fi

echo
echo "Done: ${BUNDLE_TGZ}"
du -h "$BUNDLE_TGZ" | awk '{print "Size: " $1}'
echo "Transfer the tarball **and** its .sha256 / .sig / .sha256.sig companions."
echo "On the target: AIM_AIRGAP_PUBKEY=pub.pem deploy/airgap/verify-bundle.sh ${BUNDLE_TGZ}"
echo "Then untar and run ./install-offline.sh"
echo "See docs/deployment/air-gapped-install.md for the full procedure."
