#!/usr/bin/env python3
"""Mint stack-owned secrets into the local gitignored `.env`.

Parity with dogfood `./stack init`: gatehouse fails closed without
`GATEHOUSE_WEBHOOK_SECRET`, so bare `docker compose up` / `make dev` must
land a real value in `.env` rather than interpolating empty (AIM-437 / AIM-213).

Mechanism only — never print secret values.
"""

from __future__ import annotations

import os
import re
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"

# (env key, token_urlsafe nbytes) — same generator dogfood uses for this secret.
OWNED_SECRETS: tuple[tuple[str, int], ...] = (
    # Gatehouse verifies HMAC on every webhook and exits at startup when unset.
    ("GATEHOUSE_WEBHOOK_SECRET", 32),
)


def _read_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.is_file():
        return env
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        env[key.strip()] = value
    return env


def _set_or_append(path: Path, key: str, value: str) -> None:
    """Write key=value into path without echoing the value.

    Replaces an existing assignment (including empty) in place; otherwise
    appends. File mode ends as 0600 so the secret is not world-readable.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file():
        text = path.read_text(encoding="utf-8")
        pattern = re.compile(rf"^{re.escape(key)}=.*$", re.MULTILINE)
        if pattern.search(text):
            text = pattern.sub(f"{key}={value}", text, count=1)
        else:
            if text and not text.endswith("\n"):
                text += "\n"
            text += (
                f"\n# Minted by scripts/ensure_dev_env.py (AIM-437); do not commit.\n"
                f"{key}={value}\n"
            )
    else:
        text = (
            f"# Local stack secrets — gitignored. Generated by ensure_dev_env.py.\n"
            f"{key}={value}\n"
        )

    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(text)
    path.chmod(0o600)


def main() -> int:
    current = _read_env(ENV_PATH)
    minted: list[str] = []
    for key, nbytes in OWNED_SECRETS:
        if current.get(key):
            continue
        _set_or_append(ENV_PATH, key, secrets.token_urlsafe(nbytes))
        current[key] = "set"
        minted.append(key)

    if minted:
        print(
            f"ensure_dev_env: minted {', '.join(minted)} into {ENV_PATH.name} "
            f"(compose interpolates into containers; file is gitignored, mode 0600)",
            file=sys.stderr,
        )
    else:
        print(
            f"ensure_dev_env: {ENV_PATH.name} already has required stack-owned secrets",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
